### ISSUE TITLE
compress options and timings

### ISSUE THREAD

**Issue by kzc** [Rich-Harris/butternut#1]
Congrats on the new project! The world can never have enough JS minifiers.

Just want to make a small point about compress options and timings. To squeeze an extra couple percent in file size it's not uncommon to take 2 or 3 times as long to compute.

Consider the timings and gzipped file sizes if compress is disabled altogether in uglify and only mangle is enabled:
```
$ bin/squash -v
Butternut version 0.2.0

$ node_modules/.bin/uglifyjs -V
uglify-js 2.8.23
```
```
$ /usr/bin/time bin/squash test/fixture/input/three.js | gzip | wc -c
        1.92 real         2.02 user         0.09 sys
  130312

$ /usr/bin/time node_modules/.bin/uglifyjs test/fixture/input/three.js -m | gzip | wc -c
        1.86 real         2.04 user         0.07 sys
  129135
```
```
$ /usr/bin/time bin/squash test/fixture/input/d3.js | gzip | wc -c
        1.42 real         1.49 user         0.07 sys
   73812

$ /usr/bin/time node_modules/.bin/uglifyjs test/fixture/input/d3.js -m | gzip | wc -c
        1.47 real         1.64 user         0.06 sys
   73483
```
One can see that the uglify timings and sizes are comparable to butternut with uglify compress disabled.

If compress is enabled in uglify it's naturally going to be slower to produce a smaller result:
```
$ /usr/bin/time node_modules/.bin/uglifyjs test/fixture/input/three.js -mc | gzip | wc -c
        4.31 real         5.08 user         0.12 sys
  127816
```
but it can be sped up somewhat by disabling certain compress options at the expense of output size:
```
$ /usr/bin/time node_modules/.bin/uglifyjs test/fixture/input/three.js -mc reduce_vars=false,collapse_vars=false | gzip | wc -c
        3.68 real         4.30 user         0.11 sys
  128466
```
My only point is that everything is a tradeoff. The most bang for the compute buck comes from variable name mangling.

**Comment by Rich-Harris** [comment]
Thanks! Agree. I'm not competing with Uglify so much as with Babili, which is an order of magnitude slower. Basically I want to be able to use it with https://packd.now.sh/ — certain packages (e.g. [Preact](https://packd.now.sh/preact@8.1.0) don't currently get minified, because Uglify doesn't handle ES6 (I'm not messing around with a dev branch) and Babili is just too slow for real world use.

Butternut currently beats Babili and Closure (in simple mode — I consider advanced mode disqualified because it makes so many assumptions) with a lot of the code I've tested it with, and it beats Uglify with most ES6 codebases once you factor in transpilation. It could get smarter about `if` statements etc and narrow the gap with Uglify on ES5 codebases a bit further, but I'm not planning to sink too much time into this project.

(As an aside, from my perspective Uglify's plethora of options is a bug, not a feature. As a user I'm much too lazy to spend time researching those tradeoffs!)

It does have some bugs right now though, it's definitely not ready for production use.

**Comment by kzc** [comment]
> I'm not competing with Uglify so much as with Babili

Competition is always good - the more variety of tooling the better.

> from my perspective Uglify's plethora of options is a bug, not a feature. As a user I'm much too lazy to spend time researching those tradeoffs!

To each his own. Having a lot of options is not a problem if suitable defaults are chosen. The compress and mangle defaults for uglify favor minification size over speed, but you have the flexibility to change it. Breaking out individual options can be useful under certain circumstances. 

Best of luck with Butternut! 

By the way, if you get a chance, there's a couple of minor pull requests waiting to merge in Bublé and some issue with Rollup sub-dependencies in the most recent PR I'd appreciate if you looked at.

Feel free to close this issue.

**Comment by Rich-Harris** [comment]
> By the way, if you get a chance, there's a couple of minor pull requests waiting to merge in Bublé and some issue with Rollup sub-dependencies in the most recent PR I'd appreciate if you looked at.

I will! Been working flat out on Svelte recently, just took a short break to get this project up, but plan to do a blitz of Rollup PRs and other stuff soon
